USHIN-Inc/ushin-ui-components

package.json
src/App.tsx
src/components/Point.tsx
src/components/Region.tsx
yarn.lock

* replaced contenteditable with textarea + submit button
* new points come with placeholder but no text
* submit only works when point.content is truthy

handlePointDelete, handlePointUpdate, & textarea

---

src/App.tsx
src/components/SemanticScreen.tsx

* update App message state logic to reflect this change

* pass message object from app to SemanticScreen component

---

src/App.tsx
src/components/Placeholder.tsx
src/components/Point.tsx
src/components/Region.tsx
src/components/SemanticScreen.tsx
src/constants/initialState.ts
src/interfaces.d.ts

and other changes, see individual commits

Added placeholder point

---

src/components/Region.tsx
src/components/SemanticScreen.tsx

* focus point only renders once, in focus region (no dupe in other region)
* placeholder doesn't render in focus region, can add it back in later
* import message into semscreen instead of importing just author and points

* clicking focus region no longer crashes the app

---

src/components/FocusRegion.tsx
src/components/Placeholder.tsx
src/components/Point.tsx
src/components/Region.tsx
src/components/SemanticScreen.tsx
src/components/StyledRegion.ts
src/components/StyledSemanticScreen.ts
src/index.css
src/index.tsx

+ fixed some visual bugs leftover after removing bootstrap
+ improved logic for setting focus on newly created points

media query to hide minimized region on small screens

---

src/App.tsx
src/components/FocusRegion.tsx
src/components/SemanticScreen.tsx
src/constants/AppState.ts

Automatically create points when regions expand and set chooseShapes when no focus point

---

src/components/FocusRegion.tsx
src/components/Point.tsx
src/components/Region.tsx

* fixed type of region prop in Region.tsx and FocusRegion.tsx

* made some style changes to StyledTextArea

---

src/components/FocusPoint.tsx
src/components/FocusRegion.tsx
src/components/Placeholder.tsx
src/components/Point.tsx
src/components/StyledFocusRegion.ts

* style changes in FocusPoint: made point image bigger
* changed margins in FocusPoint, Point, and Placeholder
* deleted all styles related to border in StyledFocusRegion
* no longer passing props to StyledFocusRegion
* changed margin-bottom in Placeholder to 5%

* style changes in FocusRegion: centered the focus point

---

src/components/Point.tsx
src/components/Region.tsx

up and down arrow to move between points

---

src/components/Region.tsx
src/components/SemanticScreen.tsx
src/dataModels.ts

other minor cleanup from transition to redux

fixed a bug when clicking focus region

---

package.json
src/actions/messageActions.ts
src/components/FocusPoint.tsx
src/components/Point.tsx
src/reducers/editingPoint.ts
src/reducers/message.ts
src/reducers/store.ts
yarn.lock

1. Fixes a redux bug where mapStateToProps was returning undefined.
2. Has the mouse cursor focus on the empty point created when clicking on a region.

Eric bug fixes

---

src/components/Banner.tsx
src/components/Point.tsx
src/components/Region.tsx
src/components/SemanticScreenLogic.tsx
src/dataModels.ts
src/reducers/initialState.ts

Banner shows near points which are quotes from other messages

---

package.json
src/App.tsx
src/components/FocusPoint.tsx
src/components/FocusRegion.tsx
src/components/Point.tsx
src/components/Region.tsx
src/components/SemanticScreen.tsx
src/components/SemanticScreenLogic.tsx
src/hooks/useDragPoint.ts
src/serviceWorker.ts
src/setupTests.ts
yarn.lock

added prettier and yarn lint script back in

readOnly prop added to SemanticScreen component

---

src/components/SemanticScreenLogic.tsx
src/components/ShapesRim.tsx

added prettier and yarn lint script back in

simplify how props.showShapes conditionally renders ShapesRim.tsx

---

src/components/Point.tsx
src/components/Region.tsx
src/constants/React-Dnd.tsx
src/hooks/useDragPoint.ts

In order to do this, added quoted attribute to DraggablePointType

* prevent quoted points from being recategorized with the wrong shape

---

src/App.tsx
src/actions/constants.ts
src/actions/messageActions.ts
src/components/Point.tsx
src/components/Region.tsx
src/components/SemanticScreen.tsx
src/reducers/initialState.ts
src/reducers/message.ts
src/reducers/store.ts

component accepts message and onMessageChange callback

---

src/actions/cursorPositionActions.ts
src/components/FocusRegion.tsx
src/components/MeritsRegion.tsx
src/components/Point.tsx
src/components/Region.tsx
src/components/SemanticScreen.tsx
src/components/SemanticScreenLogic.tsx
src/reducers/cursorPosition.ts
src/reducers/message.ts

* replace if statement with short circuit evaluation

---

dist/components/FocusPoint.js
dist/components/FocusRegion.js
dist/components/Placeholder.js
dist/components/Point.js
dist/components/Region.js
dist/components/SemanticScreenLogic.js
dist/components/SevenShapes.js
src/components/Banner.tsx
src/components/FocusPoint.tsx
src/components/FocusRegion.tsx
src/components/MeritsRegion.tsx
src/components/Placeholder.tsx
src/components/Point.tsx
src/components/Region.tsx
src/components/SemanticScreenLogic.tsx
src/components/SevenShapes.tsx

Added SevenShapes functionality

---

src/App.tsx
src/actions/constants.ts
src/actions/selectPointActions.ts
src/components/Point.tsx
src/components/SemanticScreen.tsx
src/reducers/selectedPoints.ts
src/reducers/store.ts

Adds the selected points state to redux. I commented out the piece of code that toggles the main point, let me know what you want to do with this.

add selected points state to redux

---

dist/App.js
dist/actions/constants.js
dist/actions/panelsActions.js
dist/components/Point.js
dist/index.js
dist/reducers/cursorPosition.js
dist/reducers/message.js
dist/reducers/panels.js
dist/reducers/selectedPoints.js
dist/reducers/store.js
src/actions/panelsActions.ts
src/index.tsx
src/reducers/cursorPosition.ts
src/reducers/message.ts
src/reducers/panels.ts
src/reducers/selectedPoints.ts
src/reducers/store.ts

* ran prettier and rebuilt dist/

* deleted unused variables in src/reducers/cursorPosition.ts

---

src/actions/cursorPositionActions.ts
src/actions/expandedRegionActions.ts
src/components/PanelButton.tsx
src/components/Point.tsx
src/components/ShapeRegion.tsx
src/reducers/cursorPosition.ts
src/reducers/expandedRegion.ts

fixed arrow key navigation in chrome, refactored setCursorPosition reducer function

---

src/App.tsx
src/actions/constants.ts
src/actions/panelsActions.ts
src/components/StyledSemanticScreen.ts
src/reducers/panels.ts

panel style fixes 

---

src/App.tsx
src/components/PanelButton.tsx
src/components/ParkingSpace.tsx
src/components/SemanticScreen.tsx
src/components/StyledSemanticScreen.ts
src/reducers/message.ts

minor style fixes and improvements

panel button hover style

---

src/App.tsx
src/components/FocusPoint.tsx
src/components/FocusRegion.tsx
src/components/MainPointShape.tsx
src/components/NewPointButton.tsx
src/components/PanelButton.tsx
src/components/Point.tsx
src/components/PointHoverOptions.tsx
src/components/ShapeRegion.tsx
src/components/StyledMeritsRegion.ts
src/components/StyledPoint.tsx
src/components/StyledRegion.ts

* minor style tweaks (scrollbars no longer appear on hover)
* resolved warning related to PointHoverOptions width and height

* fixed drag and drop refs

---

src/actions/messagesActions.ts
src/components/FocusPoint.tsx
src/components/FocusRegion.tsx
src/components/NewMessageButton.tsx
src/components/Point.tsx
src/components/SemanticScreen.tsx
src/components/ShapeRegion.tsx
src/reducers/messages.ts
src/reducers/points.ts
src/reducers/selectedPoints.ts

* also, prevent creation of many empty messages
* ran prettier

* fix deletion of empty messages when switching currentMessage

---

src/App.tsx
src/components/Banner.tsx
src/components/FocusPoint.tsx
src/components/FocusRegion.tsx
src/components/MessageListItem.tsx
src/components/NewMessageButton.tsx
src/components/ParkingRegion.tsx
src/components/Point.tsx
src/components/PointHoverOptions.tsx
src/components/RegionPoint.tsx
src/components/RightPanelContents.tsx
src/components/SemanticScreen.tsx
src/components/ShapeRegion.tsx
src/components/StyledPoint.tsx
src/components/StyledRegion.ts
src/dataModels/dataModels.ts
src/reducers/messages.ts

* added MessageWrapper
* bug fixes

preliminary right panel

---

package.json
src/App.tsx
src/actions/constants.ts
src/actions/dbActions.ts
src/actions/searchActions.ts
src/components/RightPanelContents.tsx
src/reducers/search.ts
src/reducers/store.ts
yarn.lock

Added new actions and reducers for search, integrated search with the DB

Integrated search from DB

---

package.json
src/actions/dbActions.ts
src/actions/draftMessagesActions.ts
src/components/Point.tsx
src/components/RightPanelContents.tsx
src/components/StyledPoint.tsx
src/reducers/db.ts
src/reducers/draftMessages.ts
src/reducers/draftPoints.ts
src/reducers/messages.ts
src/reducers/points.ts
yarn.lock

Commit 5811b0a368cabcc626c0f653293e2cef2fed1ca9 is the one to look at. Please note that when you go to publish a message, the app crashes because the author information returned from the db is different from the author information passed to the db. In order for this pull request to be functional, we need to first initialize redux with the proper author information as generated by ushin-db. If it's as simple as calling db.getAuthorInfo() before creating the redux store, I can do that! Let's talk about it :)

Save message

---

src/components/Point.tsx
src/components/RightPanelContents.tsx
src/components/StyledPoint.tsx
src/reducers/points.ts

also, autosize textarea wrapper

Right panel search form

---

package.json
src/App.tsx
src/actions/constants.ts
src/actions/dbActions.ts
src/actions/displayAppActions.ts
src/actions/userIdentitiesActions.ts
src/components/RightPanelContents.tsx
src/constants/initialState.ts
src/dataModels/dataModels.ts
src/reducers/displayApp.ts
src/reducers/draftMessages.ts
src/reducers/store.ts
src/reducers/userIdentities.ts
yarn.lock

* added reducer to handle creation of user identities
* added state to track whether the app displays or not (only render the app after the db has loaded)
* created UserIdentity type signature with _rev

* author info comes from PouchDB
